language: python
dist=xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e . -e .[tests]
script:
  - python3 -m unittest discover -v -t unittest_parallel -s unittest_parallel/tests
