dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e . -e .[tests]
script:
  - python3 -m coverage run --branch --source unittest_parallel -m unittest discover -v -t unittest_parallel -s unittest_parallel/tests
  - python3 -m coverage xml
after_success:
  - codecov
