dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -e . -e .[tests] coverage
script:
  - python3 -m coverage run --branch --source src -m unittest discover -v -t src -s src/tests
  - python3 -m coverage xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
